name: Multi-OpenWrt Images
  
on:
  push:
    paths: 
      - '.github/workflows/push.yml'
      
env:
  TZ: Asia/Shanghai
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SSH_PUB: ${{ secrets.SSH_PUB }}
  EMAIL_GITHUB: ${{ secrets.EMAIL_GITHUB }}
  NAME_GITHUB: ${{ secrets.NAME_GITHUB }}
  LZ_YLOGIN: ${{ secrets.LZ_YLOGIN }}
  LZ_PHPDISK: ${{ secrets.LZ_PHPDISK }}
  
jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Install rclone #安装rclone
        run: curl https://rclone.org/install.sh | sudo bash
        
      - name: Lanzou 蓝奏云
        run: |
          which python
          which pip
          pip -V
          python -V
          pip install lanzou-api
          ls -al
          python python/lzy.py $LZ_YLOGIN $LZ_PHPDISK
          
          
        
        
        
        
        
        
