name: UPload 蓝奏云 
       
on:
  push:
    paths: 
      - '.github/workflows/push.yml'
      
env:
  TZ: Asia/Shanghai
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SSH_PUB: ${{ secrets.SSH_PUB }}
  EMAIL_GITHUB: ${{ secrets.EMAIL_GITHUB }}
  NAME_GITHUB: ${{ secrets.NAME_GITHUB }}
  
jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: install 
        run: |
          sudo apt update
          sudo apt install rename
          
      - name: creat and rename
        run: |
          mkdir RELEASE && cd RELEASE
          export RELEASE_dir=`pwd`
          echo "RELEASE_dir=$RELEASE_dir" >> $GITHUB_ENV
          truncate -s 99M 1.6-360T7-108M-hanwckf-openclash-ssrplus-passwall-BIN.tar.gz
          truncate -s 99M 2.5-360T7-108M-ImmortalWrt-openclash-factory.tar.gz
          truncate -s 99M 1.6-360T7-108M-hanwckf-openclash-ssrplus-passwall-sysupgrade.tar.gz
          rename "s/openclas/猫/" *
          rename "s/ssrplus/师夷/" *
          rename "s/passwall/pa斯沃/" *
          rename "s/-360T7//" *
          
      - name: creat
          # sudo python3 -m pip install --upgrade pip
          # sudo pip3 install requests-toolbelt
        run: |
          git clone https://github.com/levenwindy/LanZouCloud-API && cd LanZouCloud-API
          sudo pip install -U pip
          sudo pip install -r requirements.txt
          # sudo pip3 install requests-toolbelt
          sudo python3 setup.py install 
          
      - name: UPLOAD
      # 'HISTORY' LZ云目录名
        run: |
          python3 python/lzy.py ${{ secrets.LZ_YLOGIN }} ${{ secrets.LZ_PHPDISK }}  \
                  'HISTORY'  'latest_TEST'  $RELEASE_dir
        
          
          
        
        
        
        
        
        
