name: Multi-OpenWrt Images
  
on:
  push:
    paths: 
      - '.github/workflows/push.yml'
      
env:
  TZ: Asia/Shanghai
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SSH_PUB: ${{ secrets.SSH_PUB }}
  EMAIL_GITHUB: ${{ secrets.EMAIL_GITHUB }}
  NAME_GITHUB: ${{ secrets.NAME_GITHUB }}

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Install rclone #安装rclone
        run: curl https://rclone.org/install.sh | sudo bash
        
      - name: Unzip config #解压配置文件
        run: |
          sudo -E apt-get -qq install  zip unzip
          mkdir -p ~/.config/rclone/
          unzip -P ${{ secrets.PASSWD_rclone }} rclone.zip -d ~/.config/rclone/
          ls -al ~/.config/rclone/
        
        
        
        
        
        
