name: Multi-OpenWrt Images
  
on:
  push:
    paths: 
      - '.github/workflows/push.yml'
      
env:
  TZ: Asia/Shanghai

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: PUSH
          # -u 是预设 ，下次 直接 push
            # git branch -M master
            # 推送 master 到 RouterFirmware 节点
            # -M master 指定分支
        run: |
            if [ ! -f ~/.ssh ];then 
              mkdir -p ~/.ssh  && echo '创建 .ssh 文件夹 成功 '
            fi
            tee << EOF > ~/.ssh/id_rsa
            ${{ secrets.SSH_KEY }}
            EOF
            echo '创建 id_rsa 文件 成功 '
            echo '1'
            git config --global user.email ${{ secrets.EMAIL_GITHUB }} && echo 'git 邮箱设置成功 '
            echo '2'
            git config --global user.name  ${{ secrets.NAME_GITHUB }}
            echo '3'
            mkdir openwrt
            cd openwrt
            touch 360.txt
            git init
            git commit -m "提交信息" $$ echo '提交信息成功 '
            git branch -M master
            git add *
            git remote add RouterFirmware git@github.com:levendwindy/RouterFirmware.git
            git push -u RouterFirmware master

        
        
        
        
        
        
        
