name: Multi-OpenWrt Images
  
on:
  workflow_dispatch:
    inputs:
      INPUT_TARGET:
        description: "Target to build (platform/target/subtarget)"
        required: false
        default: "all"
  push:
    paths: 
      - '.github/workflows/release.yml'
      
env:
  TZ: Asia/Shanghai
  # 下载线程数 DOWNLOAD
  DOWNLOAD: 8
  # 编译核心数 0 默认最多
  NPROC: 0
  # 构建原版Uboot
  Vanilla: true
  # 环境 true
  ENVIRONMENT: true
  # 快速编译
  FAST: true
  # 开启SSH
  SSH: tru 
  # 开启SSH 原厂固件
  VanillaUboot: true
  # 编译插件版   
  PLUGINver: true

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    steps:
    - name: Generate release tag
      id: tag
    #   if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      #  [ $UPLOAD_COWTRANSFER = true ] && echo "🔗 [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
     #   [ $UPLOAD_WETRANSFER = true ] && echo "🔗 [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt
      run: |
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d)"
        touch release.txt 
        echo "🔗 [Cowtransfer]" >> release.txt
        echo "🔗 [WeTransfer]" >> release.txt
        echo "::set-output name=status::success"

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: release.txt
